'use strict';

const Razorpay = require('razorpay');
const logger = require('../utils/logger');

const keyId = (process.env.RAZORPAY_KEY_ID || '').trim();
const keySecret = (process.env.RAZORPAY_KEY_SECRET || '').trim();

if (!keyId || !keySecret) {
    logger.error('❌ CRITICAL: RAZORPAY_KEY_ID or RAZORPAY_KEY_SECRET is missing in .env!');
}

const razorpay = new Razorpay({
    key_id: keyId,
    key_secret: keySecret,
});

logger.info('🚀 Razorpay: Service Initialized');

/**
 * Creates a Razorpay Order
 * @param {number} amount - Amount in INR
 * @param {string} receipt - Custom order ID generated by the app
 * @param {object} notes - Key-value metadata
 * @returns {Promise<object>} Razorpay Order Object
 */
async function createOrder(amount, receipt, notes = {}) {
    const amountInPaise = Math.round(Number(amount) * 100);
    const options = {
        amount: amountInPaise,
        currency: 'INR',
        receipt: receipt,
        notes: notes,
    };
    return await razorpay.orders.create(options);
}

module.exports = {
    razorpay,
    createOrder,
};
