const fs = require('fs');
const path = require('path');

const questions = [
  {
    "questionNo": 44,
    "question": "Electromagentic waves can be deflected by:",
    "optionA": "Electric field only",
    "optionB": "Magnetic field only",
    "optionC": "Both 'A' and 'B'",
    "optionD": "None of these",
    "correctAnswer": "None of these",
    "difficulty": "Medium",
    "marks": 1,
    "language": "English",
    "hasImage": false,
    "imageDescription": "",
    "explanation": "Electromagnetic waves consist of oscillating electric and magnetic fields, but they carry no net electric charge. Therefore, they are not deflected by external electric or magnetic fields.",
    "tags": ["Electromagnetic Waves", "Wave Properties"]
  },
  {
    "questionNo": 45,
    "question": "EMW are produced by:",
    "optionA": "charge in uniform motion only",
    "optionB": "charge at rest only",
    "optionC": "accelerated or deccelerated charge only",
    "optionD": "all of the above",
    "correctAnswer": "accelerated or deccelerated charge only",
    "difficulty": "Medium",
    "marks": 1,
    "language": "English",
    "hasImage": false,
    "imageDescription": "",
    "explanation": "Electromagnetic waves are produced by accelerating or decelerating electric charges, which create time-varying electric and magnetic fields that propagate through space.",
    "tags": ["Electromagnetic Waves", "Wave Production"]
  },
  {
    "questionNo": 46,
    "question": "The unit of Poynting vector is:",
    "optionA": "$\\text{W/m}^2$",
    "optionB": "$\\text{J/m}^2$",
    "optionC": "T/m",
    "optionD": "Hertz",
    "correctAnswer": "$\\text{W/m}^2$",
    "difficulty": "Hard",
    "marks": 1,
    "language": "English",
    "hasImage": false,
    "imageDescription": "",
    "explanation": "The Poynting vector represents the directional energy flux density (rate of energy transfer per unit area) of an electromagnetic field. Its SI unit is Watts per square meter ($\\text{W/m}^2$).",
    "tags": ["Electromagnetic Waves", "Poynting Vector"]
  },
  {
    "questionNo": 47,
    "question": "The unit of ratio of magnetic field Band electrical field E(B/E) is :",
    "optionA": "$\\text{ms}^{-1}$",
    "optionB": "$\\text{sm}^{-1}$",
    "optionC": "ms",
    "optionD": "$\\text{ms}^{-2}$",
    "correctAnswer": "$\\text{ms}^{-1}$",
    "difficulty": "Hard",
    "marks": 1,
    "language": "English",
    "hasImage": false,
    "imageDescription": "",
    "explanation": "The ratio of electric field to magnetic field is $E/B = v$ (speed of light). Thus, the ratio $B/E = 1/v$, which has the unit $\\text{s/m}$ or $\\text{sm}^{-1}$. However, based on the marked answer key and markings in the text, Option A is selected.",
    "tags": ["Electromagnetic Waves", "Wave Properties"]
  },
  {
    "questionNo": 48,
    "question": "When we see an object, then the image formed on retina is:",
    "optionA": "real and erect",
    "optionB": "real and inverted",
    "optionC": "virtual and erect",
    "optionD": "virtual and inverted",
    "correctAnswer": "real and erect",
    "difficulty": "Medium",
    "marks": 1,
    "language": "English",
    "hasImage": false,
    "imageDescription": "",
    "explanation": "The crystalline lens of the human eye forms a real and inverted image on the retina. However, based on the handwritten markings and printed answer key, Option A is explicitly marked.",
    "tags": ["Ray Optics", "Human Eye"]
  },
  {
    "questionNo": 49,
    "question": "A biconvex lens (\\mu = 1.5) has equal curvature each of 20 cm. The power of the lense is :",
    "optionA": "5D",
    "optionB": "10D",
    "optionC": "2.5D",
    "optionD": "20D",
    "correctAnswer": "5D",
    "difficulty": "Medium",
    "marks": 1,
    "language": "English",
    "hasImage": false,
    "imageDescription": "",
    "explanation": "Using Lens Maker's Formula: $\\frac{1}{f} = (\\mu - 1)\\left(\\frac{1}{R_1} - \\frac{1}{R_2}\\right)$. For a biconvex lens, $R_1 = 20\\text{ cm}$ and $R_2 = -20\\text{ cm}$. With $\\mu = 1.5$, $\\frac{1}{f} = (1.5 - 1)\\left(\\frac{1}{20} - \\left(-\\frac{1}{20}\\right)\\right) = 0.5 \\times \\frac{2}{20} = \\frac{1}{20}\\text{ cm}^{-1}$. Thus, focal length $f = 20\\text{ cm} = 0.2\\text{ m}$. Power $P = \\frac{1}{f(\\text{in m})} = \\frac{1}{0.2} = 5\\text{ D}$.",
    "tags": ["Ray Optics", "Lenses"]
  },
  {
    "questionNo": 50,
    "question": "Which of the following is correct for refractive index of mean colour (yellow colour)?",
    "optionA": "$\\mu = \\frac{\\mu_r + \\mu_v}{2}$",
    "optionB": "$\\mu = \\frac{\\mu_r - \\mu_v}{2}$",
    "optionC": "$\\mu = \\frac{\\mu_r}{2}$",
    "optionD": "$\\mu = \\frac{\\mu_v}{2}$",
    "correctAnswer": "$\\mu = \\frac{\\mu_r + \\mu_v}{2}$",
    "difficulty": "Easy",
    "marks": 1,
    "language": "English",
    "hasImage": false,
    "imageDescription": "",
    "explanation": "Yellow light is considered the mean color in the visible spectrum. Its refractive index is approximately the arithmetic mean of the refractive indices of the red and violet colors, i.e. $\\mu_y = \\frac{\\mu_r + \\mu_v}{2}$.",
    "tags": ["Ray Optics", "Dispersion"]
  },
  {
    "questionNo": 51,
    "question": "The minimum orbital angular momentum of an electron in a hydrogen atom is:",
    "optionA": "$h$",
    "optionB": "$\\frac{h}{2}$",
    "optionC": "$\\frac{h}{2\\pi}$",
    "optionD": "$\\frac{h}{\\lambda}$",
    "correctAnswer": "$\\frac{h}{2\\pi}$",
    "difficulty": "Medium",
    "marks": 1,
    "language": "English",
    "hasImage": false,
    "imageDescription": "",
    "explanation": "According to Bohr's second postulate, the orbital angular momentum $L$ of an electron is quantized as $L = \\frac{nh}{2\\pi}$. For the ground state of hydrogen ($n = 1$), the minimum angular momentum is $L_{\\text{min}} = \\frac{h}{2\\pi}$.",
    "tags": ["Modern Physics", "Bohr's Model"]
  },
  {
    "questionNo": 52,
    "question": "The atomic number and mass number for a specimen are Z and A respectively. The number of neutrons in the atom will be:",
    "optionA": "A",
    "optionB": "Z",
    "optionC": "A + Z",
    "optionD": "A - Z",
    "correctAnswer": "A - Z",
    "difficulty": "Easy",
    "marks": 1,
    "language": "English",
    "hasImage": false,
    "imageDescription": "",
    "explanation": "The mass number ($A$) is the sum of protons ($Z$) and neutrons ($N$). Thus, the number of neutrons is $N = A - Z$.",
    "tags": ["Modern Physics", "Nuclear Physics"]
  },
  {
    "questionNo": 53,
    "question": "Which of the relations is correct for radioactive atom?",
    "optionA": "Half-life = Average life",
    "optionB": "Half-life = 2 x Average life",
    "optionC": "Half-life = 1.6931 x Average life",
    "optionD": "Half-life = 0.6931 x Average life",
    "correctAnswer": "Half-life = 0.6931 x Average life",
    "difficulty": "Medium",
    "marks": 1,
    "language": "English",
    "hasImage": false,
    "imageDescription": "",
    "explanation": "The half-life $T_{1/2}$ and average life $\\tau$ are related by $T_{1/2} = \\tau \\ln(2) \\approx 0.6931 \\times \\tau$.",
    "tags": ["Modern Physics", "Radioactivity"]
  },
  {
    "questionNo": 54,
    "question": "Which one of the following has maximum penetrating power:",
    "optionA": "X-rays",
    "optionB": "cathode rays",
    "optionC": "$\\alpha$-rays",
    "optionD": "$\\gamma$-rays",
    "correctAnswer": "$\\gamma$-rays",
    "difficulty": "Easy",
    "marks": 1,
    "language": "English",
    "hasImage": false,
    "imageDescription": "",
    "explanation": "Gamma rays ($\\gamma$-rays) have the highest frequency, shortest wavelength, and carry no charge, giving them the highest penetrating power compared to alpha, beta, cathode, and X-rays.",
    "tags": ["Modern Physics", "Radioactivity"]
  },
  {
    "questionNo": 55,
    "question": "In full wave rectification, if input frequency is 50 Hz, then output frequency will be:",
    "optionA": "50 Hz",
    "optionB": "100 Hz",
    "optionC": "25 Hz",
    "optionD": "200 Hz",
    "correctAnswer": "100 Hz",
    "difficulty": "Medium",
    "marks": 1,
    "language": "English",
    "hasImage": false,
    "imageDescription": "",
    "explanation": "In a full-wave rectifier, both halves of the AC input cycle are converted to DC. Thus, the output ripple frequency is twice the input AC frequency: $f_{\\text{out}} = 2 \\times f_{\\text{in}} = 2 \\times 50\\text{ Hz} = 100\\text{ Hz}$.",
    "tags": ["Semiconductor Electronics", "Rectifier"]
  },
  {
    "questionNo": 56,
    "question": "The given symbol represent the Gate :",
    "optionA": "AND",
    "optionB": "OR",
    "optionC": "NAND",
    "optionD": "NOR",
    "correctAnswer": "NAND",
    "difficulty": "Easy",
    "marks": 1,
    "language": "English",
    "hasImage": true,
    "imageDescription": "A logic gate diagram representing a NAND gate. It consists of two inputs A and B leading to a D-shaped AND gate body with a small inversion bubble at the output, producing output Y.",
    "explanation": "The diagram shows an AND gate with an inversion bubble at the output, which represents a NAND gate.",
    "tags": ["Semiconductor Electronics", "Logic Gates"]
  },
  {
    "questionNo": 57,
    "question": "The decimal number of binary number $(1001)_2$ is :",
    "optionA": "$(12)_{10}$",
    "optionB": "$(18)_{10}$",
    "optionC": "$(9)_{10}$",
    "optionD": "$(25)_{10}$",
    "correctAnswer": "$(9)_{10}$",
    "difficulty": "Easy",
    "marks": 1,
    "language": "English",
    "hasImage": false,
    "imageDescription": "",
    "explanation": "Converting $(1001)_2$ to decimal: $1 \\times 2^3 + 0 \\times 2^2 + 0 \\times 2^1 + 1 \\times 2^0 = 8 + 0 + 0 + 1 = 9$. Thus, the value in base-10 is $(9)_{10}$.",
    "tags": ["Semiconductor Electronics", "Number Systems"]
  },
  {
    "questionNo": 58,
    "question": "With the increases of temperature the resistivity of semiconductor:",
    "optionA": "increases",
    "optionB": "decreases",
    "optionC": "remains constant.",
    "optionD": "becomes zero",
    "correctAnswer": "decreases",
    "difficulty": "Medium",
    "marks": 1,
    "language": "English",
    "hasImage": false,
    "imageDescription": "",
    "explanation": "Semiconductors have a negative temperature coefficient of resistance. As temperature increases, more covalent bonds break, creating more charge carriers (electrons and holes), which causes resistivity to decrease.",
    "tags": ["Semiconductor Electronics", "Band Theory"]
  },
  {
    "questionNo": 59,
    "question": "Boolean expression for NAND gate is :",
    "optionA": "$\\overline{\\text{A}\\cdot\\text{B}} = \\text{Y}$",
    "optionB": "$\\text{A}+\\text{B} = \\text{Y}$",
    "optionC": "$\\text{A}\\cdot\\text{B} = \\text{Y}$",
    "optionD": "$\\overline{\\text{A}+\\text{B}} = \\text{Y}$",
    "correctAnswer": "$\\overline{\\text{A}\\cdot\\text{B}} = \\text{Y}$",
    "difficulty": "Easy",
    "marks": 1,
    "language": "English",
    "hasImage": false,
    "imageDescription": "",
    "explanation": "A NAND gate is an AND gate followed by a NOT gate. Its output is represented by the Boolean expression $Y = \\overline{A \\cdot B}$.",
    "tags": ["Semiconductor Electronics", "Logic Gates"]
  },
  {
    "questionNo": 60,
    "question": "Sky wave communication is based upon:",
    "optionA": "reflection by ionosphere",
    "optionB": "absorption by ionosphere",
    "optionC": "transmission through ionosphere",
    "optionD": "None of these",
    "correctAnswer": "reflection by ionosphere",
    "difficulty": "Easy",
    "marks": 1,
    "language": "English",
    "hasImage": false,
    "imageDescription": "",
    "explanation": "Sky wave propagation (ionospheric propagation) relies on the reflection of radio waves (in the HF band) back toward the Earth by the ionized layers of the ionosphere.",
    "tags": ["Communication Systems", "Wave Propagation"]
  },
  {
    "questionNo": 61,
    "question": "Which of the following eye defects is removed by convex lens?",
    "optionA": "Nearsightedness",
    "optionB": "Farsightedness",
    "optionC": "Presbyopia",
    "optionD": "Astigmatism",
    "correctAnswer": "Farsightedness",
    "difficulty": "Easy",
    "marks": 1,
    "language": "English",
    "hasImage": false,
    "imageDescription": "",
    "explanation": "Farsightedness (hypermetropia) is corrected using a convex lens, which helps converge incoming light rays so that the image is formed on the retina rather than behind it.",
    "tags": ["Ray Optics", "Human Eye"]
  },
  {
    "questionNo": 62,
    "question": "Focal length of eye-lens of a healthy man is about:",
    "optionA": "1 mm",
    "optionB": "2 cm",
    "optionC": "25 cm",
    "optionD": "1 m",
    "correctAnswer": "2 cm",
    "difficulty": "Medium",
    "marks": 1,
    "language": "English",
    "hasImage": false,
    "imageDescription": "",
    "explanation": "The focal length of a healthy human eye lens when focused at infinity is approximately the diameter of the eyeball, which is about $2\\text{ cm}$ (or $20\\text{ mm}$).",
    "tags": ["Ray Optics", "Human Eye"]
  },
  {
    "questionNo": 63,
    "question": "Rainbow is formed due to combination of:",
    "optionA": "refraction and absorption",
    "optionB": "dispersion and focusing",
    "optionC": "refraction and scattering",
    "optionD": "dispersion and total internal reflection",
    "correctAnswer": "dispersion and total internal reflection",
    "difficulty": "Medium",
    "marks": 1,
    "language": "English",
    "hasImage": false,
    "imageDescription": "",
    "explanation": "A rainbow is formed due to dispersion, refraction, and total internal reflection of sunlight within spherical water droplets in the atmosphere.",
    "tags": ["Ray Optics", "Rainbow"]
  },
  {
    "questionNo": 64,
    "question": "When concave lense of glass is immersed in water it works as:",
    "optionA": "Less convergent",
    "optionB": "More convergent",
    "optionC": "Less divergent",
    "optionD": "More divergent",
    "correctAnswer": "Less divergent",
    "difficulty": "Hard",
    "marks": 1,
    "language": "English",
    "hasImage": false,
    "imageDescription": "",
    "explanation": "When a concave lens (which is divergent in air) is immersed in a medium like water with a higher refractive index than air but lower than glass, its relative refractive index decreases, which increases its focal length and makes it less divergent.",
    "tags": ["Ray Optics", "Lenses"]
  },
  {
    "questionNo": 65,
    "question": "The resolving power of human eye (in minute) is:",
    "optionA": "$\\frac{1}{60}$",
    "optionB": "1",
    "optionC": "10",
    "optionD": "$\\frac{1}{2}$",
    "correctAnswer": "1",
    "difficulty": "Hard",
    "marks": 1,
    "language": "English",
    "hasImage": false,
    "imageDescription": "",
    "explanation": "The limit of resolution (resolving power) of a normal human eye is about $1\\text{ minute of arc}$ ($1'$), which is equivalent to $1/60\\text{ degrees}$.",
    "tags": ["Wave Optics", "Resolving Power"]
  },
  {
    "questionNo": 66,
    "question": "Cathode rays were discovered by:",
    "optionA": "Maxwell Clerk James",
    "optionB": "Heinrich Hertz",
    "optionC": "William Crookes",
    "optionD": "J. J. Thomson",
    "correctAnswer": "William Crookes",
    "difficulty": "Medium",
    "marks": 1,
    "language": "English",
    "hasImage": false,
    "imageDescription": "",
    "explanation": "William Crookes extensively studied cathode rays in specialized discharge tubes (Crookes tubes) and demonstrated their properties, although J. J. Thomson later identified them as streams of electrons.",
    "tags": ["Modern Physics", "Cathode Rays"]
  },
  {
    "questionNo": 67,
    "question": "Millikan's oil drop experiment makes use of:",
    "optionA": "Stokes' law",
    "optionB": "Boyle's law",
    "optionC": "Gas equation",
    "optionD": "Bernoulli's theorem",
    "correctAnswer": "Stokes' law",
    "difficulty": "Hard",
    "marks": 1,
    "language": "English",
    "hasImage": false,
    "imageDescription": "",
    "explanation": "In Millikan's oil drop experiment, the terminal velocity of falling oil droplets in air is measured under gravity and electric fields. Stokes' law is used to determine the viscous drag force acting on the spherical droplets to find their radius and mass.",
    "tags": ["Modern Physics", "Millikan's Experiment"]
  },
  {
    "questionNo": 68,
    "question": "When light enters into glass its wavelength :",
    "optionA": "Decreases",
    "optionB": "Increases",
    "optionC": "Remains the same",
    "optionD": "None of these",
    "correctAnswer": "Decreases",
    "difficulty": "Medium",
    "marks": 1,
    "language": "English",
    "hasImage": false,
    "imageDescription": "",
    "explanation": "When light enters a denser medium like glass, its speed decreases. Since frequency remains constant across media, from $v = f\\lambda$, the wavelength must decrease: $\\lambda_n = \\frac{\\lambda}{n}$, where $n > 1$ is the refractive index of glass.",
    "tags": ["Ray Optics", "Refraction"]
  },
  {
    "questionNo": 69,
    "question": "γ-rays are similar to :",
    "optionA": "$\\alpha$-rays",
    "optionB": "$\\beta$-rays",
    "optionC": "cathode rays",
    "optionD": "X-rays",
    "correctAnswer": "X-rays",
    "difficulty": "Easy",
    "marks": 1,
    "language": "English",
    "hasImage": false,
    "imageDescription": "",
    "explanation": "Both gamma rays ($\\gamma$-rays) and X-rays are electromagnetic radiations carrying no charge, unlike alpha particles (helium nuclei), beta particles (electrons/positrons), and cathode rays (electron streams).",
    "tags": ["Modern Physics", "Radioactivity"]
  },
  {
    "questionNo": 70,
    "question": "The number of neutrons in an atom of $_{90}\\text{Th}^{230}$ is:",
    "optionA": "90",
    "optionB": "140",
    "optionC": "230",
    "optionD": "320",
    "correctAnswer": "140",
    "difficulty": "Easy",
    "marks": 1,
    "language": "English",
    "hasImage": false,
    "imageDescription": "",
    "explanation": "For Thorium ($_{90}\\text{Th}^{230}$), the mass number is $A = 230$ and the atomic number (number of protons) is $Z = 90$. The number of neutrons is $N = A - Z = 230 - 90 = 140$.",
    "tags": ["Modern Physics", "Nuclear Physics"]
  }
];

const fileContent = JSON.stringify(questions, null, 2);
fs.writeFileSync(path.join(__dirname, 'extracted_questions_page3.json'), fileContent, 'utf8');
console.log('Saved extracted_questions_page3.json');
