const fs = require('fs');
const path = require('path');

const questions = [
  {
    "questionNo": 1,
    "question": "Capacity of any condenser does not depend upon:",
    "optionA": "shape of plates",
    "optionB": "size of plates",
    "optionC": "charges on plates",
    "optionD": "distance between plates",
    "correctAnswer": "charges on plates",
    "difficulty": "Medium",
    "marks": 1,
    "language": "English",
    "hasImage": false,
    "imageDescription": "",
    "explanation": "The capacitance of a condenser depends only on its geometrical configuration (shape, size, and separation of plates) and the medium between them. It is independent of the charge on the plates.",
    "tags": ["Electrostatics", "Capacitance"]
  },
  {
    "questionNo": 2,
    "question": "The device which works of both modulation and demodulation is called:",
    "optionA": "Laser",
    "optionB": "Radar",
    "optionC": "Modem",
    "optionD": "Fax",
    "correctAnswer": "Modem",
    "difficulty": "Easy",
    "marks": 1,
    "language": "English",
    "hasImage": false,
    "imageDescription": "",
    "explanation": "A modem (modulator-demodulator) is a device that converts digital signals into analog signals (modulation) for transmission and vice-versa (demodulation).",
    "tags": ["Communication Systems", "Modem"]
  },
  {
    "questionNo": 3,
    "question": "A magnet is situated near a closed conductor. Current can be produced in the conductor, if:",
    "optionA": "only magnet is in motion",
    "optionB": "only conductor is in motion",
    "optionC": "both magnet and conductor are in motion",
    "optionD": "there is relative motion between magnet and conductor",
    "correctAnswer": "there is relative motion between magnet and conductor",
    "difficulty": "Medium",
    "marks": 1,
    "language": "English",
    "hasImage": false,
    "imageDescription": "",
    "explanation": "According to Faraday's law of electromagnetic induction, an induced current is produced in a closed circuit whenever there is a relative motion between the magnet and the conductor, causing a change in magnetic flux.",
    "tags": ["Electromagnetic Induction", "Faraday's Law"]
  },
  {
    "questionNo": 4,
    "question": "Picofarad is the unit of:",
    "optionA": "electric charge",
    "optionB": "intensity of electric field",
    "optionC": "electric capacity",
    "optionD": "electric flux",
    "correctAnswer": "electric capacity",
    "difficulty": "Easy",
    "marks": 1,
    "language": "English",
    "hasImage": false,
    "imageDescription": "",
    "explanation": "Picofarad ($1\\text{ pF} = 10^{-12}\\text{ F}$) is a unit of capacitance (electric capacity).",
    "tags": ["Electrostatics", "Units and Dimensions"]
  },
  {
    "questionNo": 5,
    "question": "To convert a galvanometer into an ammeter, one needs to connect a:",
    "optionA": "low resistance in parallel",
    "optionB": "low resistance in series",
    "optionC": "high resistance in parallel",
    "optionD": "high resistance in series",
    "correctAnswer": "low resistance in parallel",
    "difficulty": "Medium",
    "marks": 1,
    "language": "English",
    "hasImage": false,
    "imageDescription": "",
    "explanation": "A galvanometer is converted into an ammeter by connecting a low resistance (called a shunt) in parallel with it to allow most of the current to bypass the galvanometer.",
    "tags": ["Magnetic Effects of Current", "Measuring Instruments"]
  },
  {
    "questionNo": 6,
    "question": "An electron of charge e moves parallel to uniform lines of force in magnetic field B with velocity v. Force acting on electron is:",
    "optionA": "evB",
    "optionB": "evB",
    "optionC": "zero",
    "optionD": "Bv/e",
    "correctAnswer": "zero",
    "difficulty": "Medium",
    "marks": 1,
    "language": "English",
    "hasImage": false,
    "imageDescription": "",
    "explanation": "The magnetic force on a moving charge is given by $F = q(\\vec{v} \\times \\vec{B}) = qvB\\sin\\theta$. Since the electron moves parallel to the magnetic field, the angle $\theta = 0^\\circ$ or $180^\\circ$, hence $\sin\\theta = 0$, and the force is zero.",
    "tags": ["Magnetic Effects of Current", "Magnetic Force"]
  },
  {
    "questionNo": 7,
    "question": "The nature of electron beams moving with uniform velocity in the same direction will be:",
    "optionA": "converging",
    "optionB": "diverging",
    "optionC": "parallel",
    "optionD": "none of these",
    "correctAnswer": "parallel",
    "difficulty": "Medium",
    "marks": 1,
    "language": "English",
    "hasImage": false,
    "imageDescription": "",
    "explanation": "Since the electrons move with uniform velocity in the same direction, the electrostatic repulsive forces are balanced by the magnetic attractive forces between parallel moving charges, keeping them moving along parallel paths.",
    "tags": ["Magnetic Effects of Current", "Cathode Rays"]
  },
  {
    "questionNo": 8,
    "question": "The fringe width in interference of light due to two coherent sources is:",
    "optionA": "proportional to wavelength",
    "optionB": "inversely proportional to wavelength",
    "optionC": "proportional to square of wavelength",
    "optionD": "inversely proportional to square of wavelength",
    "correctAnswer": "proportional to wavelength",
    "difficulty": "Medium",
    "marks": 1,
    "language": "English",
    "hasImage": false,
    "imageDescription": "",
    "explanation": "The fringe width $\\beta$ is given by $\\beta = \\frac{\\lambda D}{d}$, where $\\lambda$ is the wavelength, $D$ is the distance from the slits to the screen, and $d$ is the distance between the slits. Thus, the fringe width is directly proportional to the wavelength.",
    "tags": ["Wave Optics", "Interference"]
  },
  {
    "questionNo": 9,
    "question": "Photocell is based on:",
    "optionA": "chemical effect of current",
    "optionB": "photo-electric effect",
    "optionC": "magnetic effect of current",
    "optionD": "electro-magnetic induction",
    "correctAnswer": "photo-electric effect",
    "difficulty": "Easy",
    "marks": 1,
    "language": "English",
    "hasImage": false,
    "imageDescription": "",
    "explanation": "A photoelectric cell (photocell) is a device that converts light energy into electrical energy based on the principle of the photoelectric effect.",
    "tags": ["Modern Physics", "Photoelectric Effect"]
  },
  {
    "questionNo": 10,
    "question": "If in a logic gate output (Y) is obtained by the product of its both inputs (A.B), then the gate is:",
    "optionA": "AND",
    "optionB": "OR",
    "optionC": "NOR",
    "optionD": "NOT",
    "correctAnswer": "AND",
    "difficulty": "Easy",
    "marks": 1,
    "language": "English",
    "hasImage": false,
    "imageDescription": "",
    "explanation": "The Boolean expression for the output of an AND gate is $Y = A \\cdot B$, which is the product of its inputs.",
    "tags": ["Semiconductor Electronics", "Logic Gates"]
  },
  {
    "questionNo": 11,
    "question": "The motion of electron inside the conductor is:",
    "optionA": "Uniform",
    "optionB": "Accelerated",
    "optionC": "Drifting",
    "optionD": "Decelerated",
    "correctAnswer": "Drifting",
    "difficulty": "Medium",
    "marks": 1,
    "language": "English",
    "hasImage": false,
    "imageDescription": "",
    "explanation": "Inside a conductor in the presence of an electric field, electrons experience collisions with ions and acquire a small average velocity called the drift velocity. Thus, their motion is characterized as drifting.",
    "tags": ["Current Electricity", "Drift Velocity"]
  },
  {
    "questionNo": 12,
    "question": "If any ammeter is shunted, then the total resistance of the circuit:",
    "optionA": "increases",
    "optionB": "decreases",
    "optionC": "remains same",
    "optionD": "none of these",
    "correctAnswer": "decreases",
    "difficulty": "Medium",
    "marks": 1,
    "language": "English",
    "hasImage": false,
    "imageDescription": "",
    "explanation": "Shunting an ammeter involves connecting a low resistance in parallel with it. The parallel combination of resistors always results in an equivalent resistance that is smaller than the smallest individual resistance, thereby decreasing the total resistance of the circuit.",
    "tags": ["Current Electricity", "Measuring Instruments"]
  },
  {
    "questionNo": 13,
    "question": "In visible spectrum, which colour has larger wavelength?",
    "optionA": "Red",
    "optionB": "Yellow",
    "optionC": "Blue",
    "optionD": "Violet",
    "correctAnswer": "Red",
    "difficulty": "Easy",
    "marks": 1,
    "language": "English",
    "hasImage": false,
    "imageDescription": "",
    "explanation": "In the visible spectrum, red light has the longest wavelength (approximately $700\\text{ nm}$) and violet light has the shortest wavelength (approximately $400\\text{ nm}$).",
    "tags": ["Electromagnetic Waves", "Visible Spectrum"]
  },
  {
    "questionNo": 14,
    "question": "Which one of the following electromagnetic radiations has minimum wavelength?",
    "optionA": "Ultraviolet",
    "optionB": "X-rays",
    "optionC": "Microwaves",
    "optionD": "γ-rays",
    "correctAnswer": "γ-rays",
    "difficulty": "Medium",
    "marks": 1,
    "language": "English",
    "hasImage": false,
    "imageDescription": "",
    "explanation": "Gamma rays ($\\gamma$-rays) have the highest frequency and the shortest (minimum) wavelength in the electromagnetic spectrum.",
    "tags": ["Electromagnetic Waves", "Electromagnetic Spectrum"]
  }
];

const fileContent = JSON.stringify(questions, null, 2);
fs.writeFileSync(path.join(__dirname, 'extracted_questions_page1.json'), fileContent, 'utf8');
console.log('Saved extracted_questions_page1.json');
